
Neos:
  Form:
    presets:
      default:
        formElementTypes:
          'Wegmeister.Recaptcha:Captcha':
            superTypes:
              - 'Neos.Form:FormElement'
            renderingOptions:
              templatePathPattern: 'resource://Wegmeister.Recaptcha/Private/Form/Captcha.html'
              includeAPIScript: true
              validationErrorTranslationPackage: Wegmeister.Recaptcha
        validatorPresets:
          'Wegmeister.Recaptcha:IsValid':
            implementationClassName: Wegmeister\Recaptcha\Validation\Validator\IsValidValidator
