name: Project Validate, Bump Version, update on packagist.com

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    # - name: Install dependencies
    #  run: composer install --prefer-dist --no-progress --no-suggest

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
    
    - name: Semantic Release
      uses: codfish/semantic-release-action@master
      id: semantic
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Webhook update packagist.com
      if: steps.semantic.outputs.new-release-published == 'true'
      uses: joelwmale/webhook-action@master
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        data: ""
